import { useEffect, useState } from "react";
import { IProduct } from "../models/IProduct";
import Header from "./Header";
import ProductList from "./ProductList";
import ButtonUsage from "./ButtonUsage";
import { Container, CssBaseline } from "@mui/material";


function App() {

  const [products, setProducts] = useState<IProduct[]>([]);

  useEffect(() => {

    // What is CORS?
    // CORS (Cross-Origin Resource Sharing) allows this React frontend to communicate with the API.
    // The backend must explicitly permit requests from 'http://localhost:3000' in Program.cs for this to work. (comment generated by GPT-4o)

    fetch("http://localhost:5298/api/products")
      .then(Response => Response.json())
      .then(data => setProducts(data));

  }, [])

  return (
    <>
      <CssBaseline />
      <Header />
      <Container>
        <ProductList products={products}/><br />
      </Container>

    </>

  )
}

export default App