import { useEffect, useState } from "react";
import { IProduct } from "../models/IProduct";
import Header from "./Header";
import ProductList from "./ProductList";


function App() {

  const [products, setProducts] = useState<IProduct[]>([]);

  useEffect(() => {

    // What is CORS?
    // CORS (Cross-Origin Resource Sharing) allows this React frontend to communicate with the API.
    // The backend must explicitly permit requests from 'http://localhost:3000' in Program.cs for this to work. (comment generated by GPT-4o)

    fetch("http://localhost:5298/api/products")
      .then(Response => Response.json())
      .then(data => setProducts(data));

  }, [])


  function addProduct() {
    setProducts([...products,
    {
      id: 7,
      name: "product 6",
      description: "deneme",
      imageUrl: "1.jpg",
      price: 54000,
      isActive: true
    }]);
  }

  return (
    <>
      <Header products={products} />
      <ProductList products={products} addProduct={addProduct} />
    </>

  )
}

export default App